### ISSUE TITLE
Expose the TestAdapter as a public API

### ISSUE THREAD

**Issue by yuki24** [yuki24/artemis#21]
There is this pattern in Artemis' `spec/` that may be helpful in an actual Rails application as well:

```yml
# spec/fixtures/graphql/metaphysics/artist.yml
yayoi_kusama:
  data:
    artist:
      name: Yayoi Kusama
      bio: bio...
      birthday: 1929/03/22
```

```ruby
it "can make a GraphQL request with variables" do
  stub_graphql(Metaphysics, :artist).to_return(:yayoi_kusama)

  response = Metaphysics.artist(id: "yayoi-kusama")

  expect(response.data.artist.name).to equal("yayoi-kusama")
  expect(response.data.artist.bio).to equal("bio...")
  expect(response.data.artist.birthday).to equal("1929/03/22")

  request = requests[0]

  expect(request.operation_name).to eq('Metaphysics__Artist')
  expect(request.variables).to eq('id' => 'yayoi-kusama')
  expect(request.context).to eq({})
  expect(request.document.to_query_string).to eq(<<~GRAPHQL.strip)
    query Metaphysics__Artist($id: String!) {
      artist(id: $id) {
        name
        bio
        birthday
      }
    }
  GRAPHQL
end
```

## Open questions

 * ~What if you have `app/operations/metaphysics/mock.graphql` that conflicts with the `#mock` method?~ updated the API to `stub_graphql(Client, :call)`
 * Users can forget to chain the `#to_return` method after a `#mock` call. Is there any way to prevent users from mis-mocking?
