### ISSUE TITLE
Dynamic subdomain in endpoint

### ISSUE THREAD

**Issue by nicklloyd** [yuki24/artemis#74]
Hi there - first of all, thanks for your work on this gem!

I'm looking at a current requirement of being able to have a client that is responsible for calling Shopify's Graph, but in a way that the url can be passed in as a variable. 

The schema remains the same as it's only for Shopify, but they use subdomains to identify the shop you are calling... 

@JanStevens and I have been trading ideas, but were hoping you'd have some insight into the best/cleanest way to approach.

Cheers!

**Comment by yuki24** [comment]
Thanks for using Artemis!

How many subdomains are you dealing with? Is it just a handful you could hard-code, or you have to programmatically switch endpoints? If former, you could define multiple GraphQL endpoints in the `config/graphql.yml`:

```yml
default: &default
  ...
  # some other config
  ...

  schema_path: path/to/schema_for_shopify.json

development:
  shop1:
    <<: *default
    url: https://shop1.myshopify.com/

  shop2:
    <<: *default
    url: https://shop2.myshopify.com/

  shop3:
    <<: *default
    url: https://shop3.myshopify.com/
```

Then you should be able to use `Shop1`, `shop2`, and `shop3`.

If latter, you would probably monkey-patch Artemis. Perhaps you could add a scope to the `connection` object using a hash in the `GraphQLEndpoint` class:

https://github.com/yuki24/artemis/blob/95cd5ee963ffaf947472a93a435702ff56ca6276/lib/artemis/graphql_endpoint.rb#L67-L71

And the `Client` should pick up the right connection in here:

https://github.com/yuki24/artemis/blob/95cd5ee963ffaf947472a93a435702ff56ca6276/lib/artemis/client.rb#L213-L215

Does that helpful? Let me know if it helps solve your problem.
